<a href="https://colab.research.google.com/github/joyanto7/skm-assignments/blob/main/Asssignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
# drive mount
from google.colab import drive
drive.mount('/content/drive')
import warnings
warnings.filterwarnings('ignore')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 1. Loading and exploring the dataset

In [3]:
df = pd.read_csv('/content/drive/MyDrive/datasets/Housing.csv')

In [4]:
df.shape

(545, 13)

In [5]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [6]:
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [8]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [9]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [10]:
# target variable --> airconditiong
print("Target variable Distribution:")
print(df['airconditioning'].value_counts())

Target variable Distribution:
airconditioning
no     373
yes    172
Name: count, dtype: int64

In [11]:
# 2. Separate X (features) and y (target = 'airconditioning')

X = df.drop('airconditioning', axis=1)
y = df['airconditioning']

In [12]:
# 3. Label Encode: mainroad, guestroom, basement, hotwaterheating, prefarea

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df['mainroad'] = label_encoder.fit_transform(df['mainroad'])
df['guestroom'] = label_encoder.fit_transform(df['guestroom'])
df['basement'] = label_encoder.fit_transform(df['basement'])
df['hotwaterheating'] = label_encoder.fit_transform(df['hotwaterheating'])
df['prefarea'] = label_encoder.fit_transform(df['prefarea'])

In [13]:
# 4. One-Hot Encode: furnishingstatus

furnish_encoded = pd.get_dummies(df['furnishingstatus'], prefix = 'furnishing', dtype = int)
df = pd.concat([df, furnish_encoded], axis = 1)
df.drop('furnishingstatus', axis = 1, inplace = True)
df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishing_furnished,furnishing_semi-furnished,furnishing_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,yes,2,1,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,yes,3,0,1,0,0
2,12250000,9960,3,2,2,1,0,1,0,no,2,1,0,1,0
3,12215000,7500,4,2,2,1,0,1,0,yes,3,1,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,yes,2,0,1,0,0
5,10850000,7500,3,3,1,1,0,1,0,yes,2,1,0,1,0
6,10150000,8580,4,3,4,1,0,0,0,yes,2,1,0,1,0
7,10150000,16200,5,3,2,1,0,0,0,no,0,0,0,0,1
8,9870000,8100,4,1,2,1,1,1,0,yes,2,1,1,0,0
9,9800000,5750,3,2,4,1,1,0,0,yes,1,1,0,0,1

In [20]:
# 5. Train-test split (80% train, 20% test) — remember stratify=y

X = df.drop('airconditioning', axis=1)
y = df['airconditioning']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,    # 20% for test
    stratify=y,       # keep the same Outcome ratio in train and test
    random_state=30   # Same result every time
)

In [29]:
# 6. Scale the numeric features with StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [33]:
# 7. Run: train a LogisticRegression model, apply cross validation( 5 fold, 10 fold) and print the accuracy

from sklearn.linear_model import LogisticRegression

#create model
model = LogisticRegression(max_iter=1000)

#Train the model
model.fit(X_train_scaled, y_train)

#check accuracy on training data (optional)
train_score = model.score(X_train_scaled, y_train)
print(f"Training accuracy: {train_score:.1%}")

#check accuracy on test data
test_score = model.score(X_test_scaled, y_test)
print(f"Test accuracy: {test_score:.1%}")

Training accuracy: 77.5%
Test accuracy: 74.3%

## Cross validation

In [45]:
# 5 fold
from sklearn.model_selection import cross_val_score

# Do 5-fold cross-validation
scores = cross_val_score(
    model,           # Our model
    X_train_scaled,  # Training data
    y_train,         # Training labels
    cv=5             # 5 mini-tests
)


print("5 mini-test scores:")
for i in range(5):
    print(f"  Test {i+1}: {scores[i]:.1%}")

print(f"\nAverage: {scores.mean():.1%}")
print(f"This means our model is {scores.mean():.1%} accurate!")

5 mini-test scores:
  Test 1: 76.1%
  Test 2: 72.4%
  Test 3: 77.0%
  Test 4: 78.2%
  Test 5: 81.6%

Average: 77.1%
This means our model is 77.1% accurate!

In [47]:
# 10 fold
scores10 = cross_val_score(
    model,
    X_train_scaled,
    y_train,
    cv = 10
)

print("10 mini-test scores:")
for i in range(10):
    print(f"  Test {i+1}: {scores10[i]:.1%}")

print(f"\nAverage: {scores10.mean():.1%}")

10 mini-test scores:
  Test 1: 81.8%
  Test 2: 68.2%
  Test 3: 75.0%
  Test 4: 75.0%
  Test 5: 75.0%
  Test 6: 81.8%
  Test 7: 74.4%
  Test 8: 76.7%
  Test 9: 79.1%
  Test 10: 83.7%

Average: 77.1%